#!/bin/bash

pyfile=${PYFILE:-}

if [ -z "$pyfile" ]; then
  echo "Error: PYFILE environment variable not set."
  exit 1
fi

output_file="${pyfile}c"

echo "Compiling $pyfile ..."
python3 -m py_compile "$pyfile" && mv "${pyfile}c" "$output_file"

echo "Compilation complete."

